pipeline {
    agent any

    stages {

        stage('Deploy') {
            steps {
                sh "docker build -t back-vuelos-" + env.GIT_BRANCH + ":1.0.0-" + env.BUILD_NUMBER + " ."
                sh "docker ps | grep back-vuelos-" + env.GIT_BRANCH + " | awk '{print \$1}' | xargs -r docker stop &>/dev/null"

                script {

                    if(isUnix()) {
                        sh "docker run -d --network host -p 5000:5000 back-vuelos-" + env.GIT_BRANCH + ":1.0.0-" + env.BUILD_NUMBER
                    } else {
                        sh "docker run -d -e DB_HOST=host.docker.internal -p 5000:5000 back-vuelos-" + env.GIT_BRANCH + ":1.0.0-" + env.BUILD_NUMBER
                    }

                }


                echo 'App deployed!'
            }
        }
    }
}
